### 

POST http://localhost:8000/api/register HTTP/1.1
content-type: application/json

{
    "name": "TheCodeholic",
    "email": "test@freecodecamp.org",
    "password": "test"
}

### 

POST http://localhost:8000/api/login HTTP/1.1
content-type: application/json

{
    "username": "test",
    "password": "test"
}

### Get All Surveys
GET http://localhost:8000/api/survey

### Create Survey
POST http://localhost:8000/api/survey
Content-Type: application/json

{
  "name": "Javascript 2",
  "description": "Javascript description"
}

### Update survey
PUT http://localhost:8000/api/survey/5ed8952800aec24d00bc6661
Content-Type: application/json

{
  "name": "Javascript",
  "description": "Javascript description"
}

### Get Single Survey
GET http://localhost:8000/api/survey/5ed87aa8003d3fdb00e09332


### Delete the survey
DELETE  http://localhost:8000/api/survey/5ed896bf0014ec2700a02fda


### Get questions for survey
GET http://localhost:8000/api/survey/5ed87aa8003d3fdb00e09332/question


### Create question for survey
POST http://localhost:8000/api/question/5ed87aa8003d3fdb00e09332
Content-Type: application/json

{
  "text": "Do you want Deno with Typescript or Javascript",
  "type": "choice",
  "required": true,
  "data": {
    "multiple": false,
    "answers": ["Typescript", "Javascript"]
  }
}


### Update question
POST http://localhost:8000/api/question/f3b535d3-a305-4485-93a8-78940e719cb6
Content-Type: application/json

{
  "text": "Do you want Deno with Typescript or Javascript?",
  "type": "choice",
  "required": true,
  "data": {
    "multiple": false,
    "answers": ["Typescript", "Javascript"]
  }
}

