### Register

POST http://localhost:8000/api/register HTTP/1.1
content-type: application/json

{
    "name": "TheCodeholic",
    "email": "test@freecodecamp.org",
    "password": "test"
}

### Login

POST http://localhost:8000/api/login
Content-Type: application/json

{
    "email": "test@freecodecamp.org",
    "password": "test"
}

@token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ0ZXN0QGZyZWVjb2RlY2FtcC5vcmciLCJleHAiOjE1OTE3MzAyNzYzMDJ9.8X5GOilhzFIJYTnnP9iNSU8hAioYg8YtJ87_0vSptpg


###############################################
### SURVEYS
###############################################


### Get All Surveys
GET http://localhost:8000/api/survey
Authorization: Bearer {{token}}

### Create Survey
POST http://localhost:8000/api/survey
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Application",
  "description": "This is job application for Javascript Developer"
}

### Update survey
PUT http://localhost:8000/api/survey/5edb0ef000c8493f00025b88
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "5edb0ef000c8493f00025b88",
  "description": "5edb0ef000c8493f00025b88 long description"
}

### Get Single Survey
GET http://localhost:8000/api/survey/5edb0f14003c1c7700025b89
Authorization: Bearer {{token}}

### Delete the survey
DELETE  http://localhost:8000/api/survey/5edb0ef000c8493f00025b88
Authorization: Bearer {{token}}

###############################################
### QUESIONS
###############################################

### Get questions for survey
GET http://localhost:8000/api/survey/5edb333700fa6eb4007c7908/question
Authorization: Bearer {{token}}

### Get Single Question
GET http://localhost:8000/api/question/5edb0f87009ad01000fdb1bd
Authorization: Bearer {{token}}

### Create question for survey
POST http://localhost:8000/api/question/5edb333700fa6eb4007c7908
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "text": "Which one do you like in Deno?",
  "type": "choice",
  "required": true,
  "data": {
    "multiple": true,
    "answers": [
      "Typescript builtin support", 
      "Testing builtin support",
      "Fetch API",
      "Code formatting",
      "No node_modules. Oh Yes!!!",
      "Import from URL"
    ]
  }
}

### Update question
put http://localhost:8000/api/question/5edb34f600352601007c790b
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "text": "Your Working expreience",
  "type": "choice",
  "required": false,
  "data": {
    "multiple": false,
    "answers": ["Intern", "Junior", "Middle", "Senior"]
  }
}

### Get Single Question
DELETE http://localhost:8000/api/question/5edb363d00d83531007c790c
Authorization: Bearer {{token}}


###############################################
### ANSWERS
###############################################

GET http://localhost:8000/api/survey/5edb333700fa6eb4007c7908/question
Authorization: Bearer {{token}}
